execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=0..29}] mc 1
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=30..59}] mc 2
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=60..89}] mc 3
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=90..119}] mc 4
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=120..149}] mc 5
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=150..179}] mc 6
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=180..209}] mc 7
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=210..239}] mc 8
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=240..269}] mc 9
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=270..299}] mc 10
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=300..329}] mc 11
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=330..359}] mc 12
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=360..389}] mc 13
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=390..419}] mc 14
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=420..449}] mc 15
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=450..479}] mc 16
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=480..509}] mc 17
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=510..539}] mc 18
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=540..569}] mc 19
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=570..599}] mc 20
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=600..649}] mc 21
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=650..699}] mc 22
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=700..799}] mc 23
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=800..899}] mc 24
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=900..999}] mc 25
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=1000..1099}] mc 26
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=1100..1199}] mc 27
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=1200..1299}] mc 28
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=1300..1399}] mc 29
execute @e[type=item,name=石炭] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=1400..}] mc 30
kill @e[type=item,name=石炭]
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=0..49}] mc 3
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=50..99}] mc 6
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=100..199}] mc 9
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=200..299}] mc 12
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=300..399}] mc 15
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=400..499}] mc 18
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=500..599}] mc 21
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=600..699}] mc 24
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=700..799}] mc 27
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=800..899}] mc 30
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=900..999}] mc 33
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=1000..1099}] mc 36
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=1100..1199}] mc 39
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=1200..1299}] mc 42
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=1300..1399}] mc 45
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=1400..1499}] mc 48
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=1500..1999}] mc 51
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=2000..2999}] mc 54
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=3000..3999}] mc 57
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=4000..4999}] mc 60
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=5000..5999}] mc 63
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=6000..6999}] mc 66
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=7000..7999}] mc 69
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=8000..8999}] mc 72
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=9000..9999}] mc 75
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ scoreboard players add @s[scores={lv=10000..}] mc 78
execute @e[type=item,name=原鉄] ~~~ execute @p ~~~ xp 1 @s
kill @e[type=item,name=原鉄]